### Get all tasks

GET http://localhost:4000/tasks

### Get a task by id
GET http://localhost:4000/task/1

### Create a task
POST http://localhost:4000/task
content-type: application/json

{
    "name": "Task 2",
    "description": "Task 2 description",
    "author": "Author 2",
    "isComplete": false
}

### Update a task
PUT http://localhost:4000/task/1
content-type: application/json

{
    "name": "Task 1 updated",
    "description": "Task 1 description updated",
    "author": "Author 1 updated",
    "isComplete": true
}

### Delete a task
DELETE http://localhost:4000/task/2
